apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda-helm
  namespace: argocd
spec:
  project: rag-platform
  source:
    repoURL: https://kedacore.github.io/charts
    chart: keda
    targetRevision: 2.16.1
    helm:
      values: |
        resources:
          operator:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi
          metricServer:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          webhooks:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
