apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workloads-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rag-platform
  source:
    repoURL: https://github.com/cheikh-ak/rag-platform-gitops.git
    targetRevision: main
    path: env/dev
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: rag-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
