apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: rag-worker-scaler
  namespace: rag-dev
spec:
  scaleTargetRef:
    name: rag-worker
  pollingInterval: 15
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: nats-jetstream
      metadata:
        natsServerMonitoringEndpoint: nats-helm.nats.svc.cluster.local:8222
        account: "$G"
        stream: RAG
        consumer: rag-worker
        lagThreshold: "10"
