apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: langfuse-web
  namespace: rag-dev
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: langfuse.20.124.47.17.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: langfuse-web
                port:
                  number: 3000
